# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

environment:
  global:
    WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17453/w_BaseKit_p_2021.1.0.2664_offline.exe
    WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17392/w_HPCKit_p_2021.1.0.2682_offline.exe
    MACOS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17398/m_HPCKit_p_2021.1.0.2681_offline.dmg
    WINDOWS_CPP_COMPONENTS: intel.oneapi.win.cpp-compiler
    WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler
    WINDOWS_DPCPP_COMPONENTS: intel.oneapi.win.dpcpp-compiler
    LINUX_CPP_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
    LINUX_FORTRAN_COMPONENTS: intel-oneapi-compiler-fortran
    LINUX_DPCPP_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp
    MACOS_CPP_COMPONENTS: intel.oneapi.mac.cpp-compiler
    MACOS_FORTRAN_COMPONENTS: intel.oneapi.mac.ifort-compiler
    ONEAPI_RELEASE: 2021.1.1
    ONEAPI_RELEASE_COMPILER: 2021.1.2

  matrix:
    - job_name: build_windows_cpp
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: build_windows_fortran
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: build_windows_dpcpp
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: build_linux_apt_cpp
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_apt_fortran
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_apt_dpcpp
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_mac_cpp
      appveyor_build_worker_image: macos

    - job_name: build_mac_fortran
      appveyor_build_worker_image: macos

for:
  -
    matrix:
      only:
        - job_name: build_windows_cpp
    install:
      cmd: scripts/install_windows.bat %WINDOWS_HPCKIT_URL% %WINDOWS_CPP_COMPONENTS%
    build_script:
      cmd: scripts/build_windows.bat c++ - %ONEAPI_RELEASE%

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_windows_fortran
    install:
      cmd: scripts/install_windows.bat %WINDOWS_HPCKIT_URL% %WINDOWS_FORTRAN_COMPONENTS%
    build_script:
      cmd: scripts/build_windows.bat fortran - %ONEAPI_RELEASE%

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_windows_dpcpp
    install:
      cmd: scripts/install_windows.bat %WINDOWS_BASEKIT_URL% %WINDOWS_DPCPP_COMPONENTS%
    build_script:
      cmd: scripts/build_windows.bat dpc++ - %ONEAPI_RELEASE%

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_linux_apt_cpp
    install:
      sh: |
        scripts/setup_apt_repo_linux.sh
        scripts/install_linux_apt.sh $LINUX_CPP_COMPONENTS
    build_script:
      sh: scripts/build_linux.sh c++ $ONEAPI_RELEASE_COMPILER
  -
    matrix:
      only:
        - job_name: build_linux_apt_fortran
    install:
      sh: |
        scripts/setup_apt_repo_linux.sh
        scripts/install_linux_apt.sh $LINUX_FORTRAN_COMPONENTS
    build_script:
      sh: scripts/build_linux.sh fortran $ONEAPI_RELEASE_COMPILER
  -
    matrix:
      only:
        - job_name: build_linux_apt_dpcpp
    install:
      sh: |
        scripts/setup_apt_repo_linux.sh
        scripts/install_linux_apt.sh $LINUX_DPCPP_COMPONENTS
    build_script:
      sh: scripts/build_linux.sh dpc++ $ONEAPI_RELEASE_COMPILER

  -
    matrix:
      only:
        - job_name: build_mac_cpp
    install:
      sh: scripts/install_macos.sh $MACOS_HPCKIT_URL $MACOS_CPP_COMPONENTS
    build_script:
      sh: scripts/build_macos.sh c++

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_mac_fortran
    install:
      sh: scripts/install_macos.sh $MACOS_HPCKIT_URL $MACOS_FORTRAN_COMPONENTS
    build_script:
      sh: scripts/build_macos.sh fortran

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          bootstrapper*
          installer*
