# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: build_windows_online_scheduled

on:
  schedule:
    - cron: '0 * * * *'

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17453/w_BaseKit_p_2021.1.0.2664.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17392/w_HPCKit_p_2021.1.0.2682.exe
  WINDOWS_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17406/w_IoTKit_p_2021.1.0.1220.exe
  WINDOWS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17405/w_RenderKit_p_2021.1.0.626.exe
  ONEAPI_RELEASE: 2021.1.1

jobs:
  build_windows_all:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: install_basekit
      run: scripts/install_windows.bat $WINDOWS_BASEKIT_URL
    - name: install_hpckit
      run: scripts/install_windows.bat $WINDOWS_HPCKIT_URL
    - name: install_iotkit
      run: scripts/install_windows.bat $WINDOWS_IOTKIT_URL
    - name: install_renderkit
      run: scripts/install_windows.bat $WINDOWS_RENDERKIT_URL
    - name: build_c++
      run: scripts/build_windows.bat c++ - $ONEAPI_RELEASE
    - name: build_fortran
      run: scripts/build_windows.bat fortran - $ONEAPI_RELEASE
    - name: build_dpc++
      run: scripts/build_windows.bat dpc++ - $ONEAPI_RELEASE

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7
