# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: build_all_offline_apt_dnf_scheduled

on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17768/w_BaseKit_p_2021.2.0.2871_offline.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17762/w_HPCKit_p_2021.2.0.2901_offline.exe
  WINDOWS_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17753/w_IoTKit_p_2021.2.0.1296_offline.exe
  WINDOWS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17744/w_RenderKit_p_2021.2.0.726_offline.exe
  LINUX_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17769/l_BaseKit_p_2021.2.0.2883_offline.sh
  LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17764/l_HPCKit_p_2021.2.0.2997_offline.sh
  LINUX_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17763/l_IoTKit_p_2021.2.0.2742_offline.sh
  LINUX_AIKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17766/l_AIKit_p_2021.2.0.1101_offline.sh
  LINUX_DLFDKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17748/l_DLFDKit_p_2021.2.0.1999_offline.sh
  LINUX_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17746/l_RenderKit_p_2021.2.0.739_offline.sh
  MACOS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17714/m_BaseKit_p_2021.2.0.2855_offline.dmg
  MACOS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17643/m_HPCKit_p_2021.2.0.2903_offline.dmg
  MACOS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17584/m_RenderKit_p_2021.2.0.700_offline.dmg
  LINUX_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic,intel-oneapi-compiler-fortran

jobs:
  build_windows_all_offline:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 registrationcenter-download.intel.com
    - name: install_basekit
      run: scripts/install_windows.bat $WINDOWS_BASEKIT_URL intel.oneapi.win.dpcpp-compiler
    - name: install_hpckit
      run: scripts/install_windows.bat $WINDOWS_HPCKIT_URL intel.oneapi.win.ifort-compiler
    - name: install_iotkit
      run: scripts/install_windows.bat $WINDOWS_IOTKIT_URL intel.oneapi.win.cpp-compiler
    - name: install_renderkit
      run: scripts/install_windows.bat $WINDOWS_RENDERKIT_URL intel.oneapi.win.embree
    - name: build_c++
      run: scripts/build_windows.bat c++
    - name: build_fortran
      run: scripts/build_windows.bat fortran
    - name: build_dpc++
      run: scripts/build_windows.bat dpc++

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_all_offline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_basekit
      run: scripts/install_linux.sh $LINUX_BASEKIT_URL intel.oneapi.lin.dpcpp-cpp-compiler
    - name: install_hpckit
      run: scripts/install_linux.sh $LINUX_HPCKIT_URL intel.oneapi.lin.ifort-compiler
    - name: install_iotkit
      run: scripts/install_linux.sh $LINUX_IOTKIT_URL intel.oneapi.lin.dpcpp-cpp-compiler-pro
    - name: build_c++
      run: scripts/build_linux.sh c++
    - name: build_fortran
      run: scripts/build_linux.sh fortran
    - name: build_dpcpp
      run: scripts/build_linux.sh dpc++

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_all_offline_2:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_aikit
      run: scripts/install_linux.sh $LINUX_AIKIT_URL intel.oneapi.lin.tensorflow
    - name: install_dlfdkit
      run: scripts/install_linux.sh $LINUX_DLFDKIT_URL intel.oneapi.lin.ccl.devel
    - name: install_renderkit
      run: scripts/install_linux.sh $LINUX_RENDERKIT_URL intel.oneapi.lin.embree

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_apt:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup apt repo
      run: |
        sudo dpkg --add-architecture i386
        scripts/setup_apt_repo_linux.sh
        grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
    - name: print packages info
      run: sudo apt-cache show python3 python-jsonschema intel-oneapi-*
    - name: dry-run install all
      run: sudo apt install --dry-run intel-oneapi-*
    - name: install
      run: scripts/install_linux_apt.sh $LINUX_COMPONENTS
    - name: build
      run: scripts/build_linux.sh c++
    - name: build
      run: scripts/build_linux.sh fortran
    - name: build
      run: scripts/build_linux.sh dpc++

  build_linux_apt_toolkits:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup apt repo
      run: scripts/setup_apt_repo_linux.sh
    - name: print packages info
      run: sudo apt-cache show intel-oneapi-*
    - name: dry-run install basekit
      run: sudo apt install --dry-run intel-basekit
      if: ${{ always() }}
    - name: dry-run install hpckit
      run: sudo apt install --dry-run intel-hpckit
      if: ${{ always() }}
    - name: dry-run install iotkit
      run: sudo apt install --dry-run intel-iotkit
      if: ${{ always() }}
    - name: dry-run install aikit
      run: sudo apt install --dry-run intel-aikit
      if: ${{ always() }}
    - name: dry-run install dlfdkit
      run: sudo apt install --dry-run intel-dlfdkit
      if: ${{ always() }}
    - name: dry-run install renderkit
      run: sudo apt install --dry-run intel-renderkit
      if: ${{ always() }}
    - name: dry-run install FPGA1
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-a10gx-s10sx
      if: ${{ always() }}
    - name: dry-run install FPGA2
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-a10gx-s10sx-quartus
      if: ${{ always() }}
    - name: dry-run install FPGA3
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus19.4
      if: ${{ always() }}
    - name: dry-run install FPGA4
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus20.2
      if: ${{ always() }}
    - name: dry-run install FPGA5
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus20.3
      if: ${{ always() }}
    - name: dry-run install FPGA6
      run: sudo apt install --dry-run intel-oneapi-intelfpgadpcpp-custom-platforms-quartus20.4
      if: ${{ always() }}
    - name: install
      run: scripts/install_linux_apt.sh $LINUX_COMPONENTS
    - name: build
      run: scripts/build_linux.sh c++
    - name: build
      run: scripts/build_linux.sh fortran
    - name: build
      run: scripts/build_linux.sh dpc++

  build_linux_dnf:
    runs-on: ubuntu-20.04
    container: fedora
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup yum/dnf repo
      run: scripts/setup_yum_dnf_repo_linux.sh
    - name: install prerequisites
      run: sudo dnf -y install git make gcc g++
    - name: install
      run: scripts/install_linux_dnf.sh $LINUX_COMPONENTS
    - name: build
      run: scripts/build_linux.sh c++
    - name: build
      run: scripts/build_linux.sh fortran
    - name: build
      run: scripts/build_linux.sh dpc++

  build_macos_all_offline:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: install_basekit
      run: scripts/install_macos.sh $MACOS_BASEKIT_URL
    - name: install_hpckit
      run: scripts/install_macos.sh $MACOS_HPCKIT_URL
    - name: install_renderkit
      run: scripts/install_macos.sh $MACOS_RENDERKIT_URL
    - name: build_c++
      run: scripts/build_macos.sh c++
    - name: build_fortran
      run: scripts/build_macos.sh fortran

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7
