# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
        sudo apt-get install -qq clang-format
        python -m pip install --quiet --upgrade pip
        pip install --quiet -r requirements.txt
    - name: Run checks
      run: pre-commit run --all
