# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: linux_test

on: push

env:
  LINUX_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17431/l_BaseKit_p_2021.1.0.2659_offline.sh
  ONEAPI_RELEASE: 2021.1.1

jobs:
  build_linux_all:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: scripts/install_linux.sh $LINUX_BASEKIT_URL wrong_component_name
